{
 "title": "K8S",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Cluster - CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^.*$\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster - Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^.*$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods - Failed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{namespace=\"default\",condition=\"false\"})"
    }
   ]
  },
  {
   "title": "Cluster - Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo | veth.* | docker.* | flannel.* | cali.* | cbr.\"}[5m])) by (instance)",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo | veth.* | docker.* | flannel.* | cali.* | cbr.\"}[5m])) by (instance)",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Cluster - Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m])) by (instance)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m])) by (instance)",
     "legendFormat": "writte"
    }
   ]
  },
  {
   "title": "Error 4XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=~\"4.*\"}[2m])) by (service) * 100"
    }
   ]
  },
  {
   "title": "Error 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=~\"5.*\"}[2m])) by (service) * 100"
    }
   ]
  },
  {
   "title": "Logging",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"hotrod\"}|= \"error\""
    }
   ]
  },
  {
   "title": "Pod - Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\"}) by (name)"
    }
   ]
  },
  {
   "title": "Pod - CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])) by (name)"
    }
   ]
  }
 ]
}